name: Push to DockerHub & Scan for CIS Compliance

on: [push]

permissions: write-all

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: docker login
      env:
        DOCKERHUB_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
        DOCKERHUB_PASSWORD: ${{secrets.DOCKERHUB_PASSWORD}}
      run: |
        docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag hackai87/pre_flight_check

    - name: Docker Push
      run: docker push ${{secrets.DOCKERHUB_USERNAME}}/pre_flight_check
      

  dockle:
    name: Dockle Container Analysis
    needs: push
    runs-on: ubuntu-latest
    steps:
       # Makes sure your .dockleignore file is available to the next step
      - name: Checkout
        uses: actions/checkout@v3

      # Here you might use a docker login action, or something else
      - name: Authenticate to DockHub
        uses: docker/login-action@v2
        with:
          registery: hub.docker.com/repository/docker/hackai87/pre_flight_check
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Run Dockle
        uses: erzz/dockle-action@v1
        id: dockle
        with:
          image: ${{secrets.DOCKERHUB_USERNAME}}/pre_flight_check
          report-format: sarif
          report-name: dockle-report
          failure-threshold: warn
          exit-code: 0
          accept-extensions: pem

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: dockle-report.sarif
